Repository francoischalifour/medium-zoom, pull requests merged in 2018-03, with the labels that each got.

#41 feat(examples): Unify examples
  examples/dropbox-paper-template/.gitignore
  examples/dropbox-paper-template/README.md
  examples/dropbox-paper-template/app.js
  examples/dropbox-paper-template/index.html
  examples/dropbox-paper-template/package.json
  examples/dropbox-paper-template/src/index.js
  examples/dropbox-paper-template/src/reset.css
  examples/dropbox-paper-template/src/style.css
  examples/facebook-template/.gitignore
  examples/facebook-template/README.md
  examples/facebook-template/app.js
  examples/facebook-template/index.html
  examples/facebook-template/package.json
  examples/facebook-template/src/index.js
  examples/facebook-template/src/reset.css
  examples/facebook-template/src/style.css
  examples/react-markdown/package.json
  examples/react/README.md
  examples/react/package.json
Labels: example

#42 feat(examples): Add Vue example
  examples/vue/.gitignore
  examples/vue/README.md
  examples/vue/images/image-1.jpg
  examples/vue/images/image-2.jpg
  examples/vue/images/image-3.jpg
  examples/vue/index.html
  examples/vue/package.json
  examples/vue/src/index.js
  examples/vue/src/reset.css
  examples/vue/src/style.css
Labels: example

#36 Add compatibility table to readme
  README.md
Labels: documentation

#43 docs(README): Update README
  README.md
Labels: documentation

#47 chore(rollup): Update `banner` to `output.banner`
  rollup.config.js
Labels: tooling
